name: TV Program Schedule Updater

on:
  schedule:
    # 每天北京时间8:00和20:00各运行一次（UTC时间0:00和12:00）
    - cron: '0 0,12 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  update-schedule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.X'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml

    - name: Run TVMAO scraper
      run: python tvmao-2.py

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add tvmao.xml
        git commit -m "自动更新电视节目表 $(date +'%Y-%m-%d %H:%M')" || echo "没有变化需要提交"
        git push