name: TV Program EPG Updater

on:
  schedule:
    - cron: '0 0,12 * * *'  # UTC时间每天0点和12点（北京时间8点和20点）
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai  # 设置时区为北京时间

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml fake-useragent

    - name: Run EPG Generator
      run: |
        echo "开始生成EPG数据..."
        python tvmao.py
        if [ $? -ne 0 ]; then
          echo "::error::EPG生成失败！检查tvmao.py脚本"
          exit 1
        fi

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        if [ -s tvmao.xml ]; then
          git add tvmao.xml
          COMMIT_TIME=$(date +'%Y-%m-%d %H:%M (CST)')
          COMMIT_MSG="EPG自动更新 $COMMIT_TIME"
          git commit -m "$COMMIT_MSG"
          git push
          echo "::notice ::EPG数据已更新并提交"
        else
          echo "::error::XML文件为空或不存在，跳过提交"
          exit 1
        fi