name: TV Program EPG Updater

on:
  schedule:
    - cron: '0 0,12 * * *'  # UTC时间每天0点和12点（北京时间8点和20点）
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai  # 设置时区为北京时间

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml fake-useragent python-dateutil

    - name: Run EPG Generator
      run: |
        echo "开始生成EPG数据..."
        python tvmao.py
        if [ $? -ne 0 ]; then
          echo "::error::EPG生成失败！检查tvmao.py脚本"
          exit 1
        fi

    - name: Debug XML File
      run: |
        if [ -s tvmao.xml ]; then
          echo "XML 文件内容："
          cat tvmao.xml
        else
          echo "::error::XML文件为空或不存在"
          exit 1
        fi

    - name: Debug GZ File
      run: |
        if [ -s tvmao.xml.gz ]; then
          echo "GZ 文件存在且非空"
          echo "GZ 文件大小：$(du -h tvmao.xml.gz | cut -f1)"
        else
          echo "::error::GZ文件为空或不存在"
          exit 1
        fi

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        if [ -s tvmao.xml ] && [ -s tvmao.xml.gz ]; then
          git add tvmao.xml tvmao.xml.gz
          COMMIT_TIME=$(date +'%Y-%m-%d %H:%M (CST)')
          COMMIT_MSG="EPG自动更新 $COMMIT_TIME"

          # 拉取远程仓库的最新更改
          git pull origin main --rebase

          # 检查是否有文件变更
          if ! git diff-index --quiet HEAD --; then
            git commit -m "$COMMIT_MSG"
            git push origin main
            echo "::notice ::EPG数据已更新并提交"
          else
            echo "::warning ::没有检测到文件变更，跳过提交"
          fi
        else
          echo "::error::XML或GZ文件为空或不存在，跳过提交"
          exit 1
        fi
