name: TV Program EPG Updater

on:
  schedule:
    - cron: '0 0,12 * * *'  # UTC时间每天0点和12点（北京时间8点和20点）
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml xmlschema

    - name: Run EPG Generator
      run: |
        python tvmao.py || echo "运行遇到错误，检查日志"
        cat tvmao.log  # 输出日志

    - name: Commit changes
      if: always()
      run: |
        git config --global user.name "${{ secrets.GITHUB_USERNAME }}"
        git config --global user.email "${{ secrets.GITHUB_EMAIL }}"
        
        if [ -s tvmao.xml ]; then
          git add tvmao.xml tvmao.log
          git commit -m "EPG自动更新 $(date +'%Y-%m-%d %H:%M')"
          git push
        else
          echo "XML文件为空，跳过提交"
          exit 1
        fi