name: TV Program EPG Updater

on:
  schedule:
    - cron: '0 0,12 * * *'  # UTC时间每天0点和12点（北京时间8点和20点）
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml

    - name: Run EPG Generator
      run: |
        python tvmao.py || echo "运行遇到错误，检查日志"
        cat tvmao.log  # 输出日志

    - name: Configure Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor@github.com }}"
        
    - name: Commit and Push
      if: [ -s tvmao.xml ]
      run: |
        git add tvmao.xml tvmao.log
        git commit -m "EPG自动更新 $(date +'%Y-%m-%d %H:%M')"
        git push
      else:
        run: echo "XML文件为空，跳过提交"
  
